version: '3'
services:

  mydb:
    image: mysql:5.6
    environment:
      - MYSQL_DATABASE=kimai
      - MYSQL_USER=kimaiu
      - MYSQL_PASSWORD=kimaip
      - MYSQL_ROOT_PASSWORD=changeme
    volumes:
        - ./mysql:/var/lib/mysql
    command: --default-storage-engine innodb
    restart: always

  nginx:
    image: nginx:latest
    ports:
        - 8001:80
    volumes:
      - ./codebase:/opt/shared_kimai
      - ./nginx_site.conf:/etc/nginx/conf.d/default.conf

  kimai_fpm:
    image: kimai/kimai2:fpm-alpine-master
    environment:
        - APP_ENV=dev
        - TRUSTED_HOSTS=localhost
        - DATABASE_URL=mysql://kimaiu:kimaip@mydb/kimai
        - ADMINMAIL=kimai@example.com
        - ADMINPASS=changeme123
    volumes:
      - ./codebase:/opt/shared_kimai
    entrypoint: /nginx-startup.sh
