apiVersion: v2
name: kimai2
description: A Helm chart for Kubernetes
type: application
version: 1.0.0
appVersion: "apache"

dependencies:
  - name: common
    version: 0.x.x
    repository: https://charts.bitnami.com/bitnami
  - name: mariadb
    repository: https://charts.bitnami.com/bitnami
    version: 9.x.x
    condition: mariadb.enabled
