# act -j build -W ./.github/workflows/build-multiarch.yml --secret-file  .dockerhub.secrets
name: 'Build multiarch'

on:
  workflow_dispatch:
  # repository_dispatch:
    # types: [kimai_release]

jobs:
  build:
    strategy:
      matrix:
        type: [dev,prod]
        server: [fpm,apache]
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install buildx
        uses: docker/setup-buildx-action@v2

      - name: Install lastversion
        run: sudo apt-get update -y; sudo apt-get install --no-install-recommends -y python3 python3-pip; pip install lastversion

      - name: Login to DockerHub
        uses: docker/login-action@v1.12.0
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_PASSWORD}}

      - name: get lastest 1.x version
        id: remote_version
        run: echo "::set-output name=version::$(lastversion https://github.com/kevinpapst/kimai2 --only '~^1\.')"

      - name: build ${{ matrix.server }} ${{ matrix.type }}
        run: echo kimai/kimai2:${{ matrix.type }}-${{ matrix.server }}

      - name: Build
        uses: docker/build-push-action@v2
        with:
          context: .
          build-args: |
            KIMAI=${{steps.remote_version.outputs.version}}
            TIMEZONE=Europe/London
            BASE=${{ matrix.server }}
          target: ${{ matrix.type }}
          platforms: linux/arm64,linux/amd64,linux/arm/v8,linux/arm/v7 #,linux/arm/v6
          tags: |
            kimai/kimai2:${{ matrix.server }}-${{ matrix.type }}
            kimai/kimai2:${{ matrix.server }}-${{steps.remote_version.outputs.version}}-${{ matrix.type }}
          push: true

  tag:
    runs-on: ubuntu-latest
    steps:

      - name: Login to DockerHub
        uses: docker/login-action@v1.12.0
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_PASSWORD}}

      - name: Pull images
        run: |
          docker pull kimai/kimai2:fpm
          docker pull kimai/kimai2:fpm-dev
          docker pull kimai/kimai2:apache
          docker pull kimai/kimai2:apache-dev

      - name: Tag fpm
        run: |
          docker tag kimai/kimai2:fpm kimai/kimai2:fpm-prod
          docker push kimai/kimai2:fpm

      - name: Tag fpm latest
        run: |
          docker tag kimai/kimai2:fpm kimai/kimai2:fpm-latest
          docker push kimai/kimai2:fpm-latest

      - name: Tag latest
        run: |
          docker tag kimai/kimai2:fpm kimai/kimai2:latest
          docker push kimai/kimai2:latest

      - name: Tag prod
        run: |
          docker tag kimai/kimai2:fpm kimai/kimai2:prod
          docker push kimai/kimai2:prod

      - name: Tag apache
        run: |
          docker tag kimai/kimai2:apache kimai/kimai2:apache-prod
          docker push kimai/kimai2:apache

      - name: Tag apache latest
        run: |
          docker tag kimai/kimai2:apache kimai/kimai2:apache-latest
          docker push kimai/kimai2:apache-latest

      - name: Tag dev
        run: |
          docker tag kimai/kimai2:apache-dev kimai/kimai2:dev
          docker push kimai/kimai2:dev
