name: 'Build release'

on:
  workflow_dispatch:
  repository_dispatch:
    types: [kimai_release]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Set vars from payload
        run: echo "kv=${{ github.event.client_payload.release.tag_name }}" >> $GITHUB_ENV
        if: github.event.client_payload != null

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: install lastversion
        run: sudo apt-get update -y; sudo apt-get install --no-install-recommends -y python3 python3-pip; pip install lastversion

      - name: check remote lastversion
        id: remote_version
        run: echo "::set-output name=version::$(lastversion https://github.com/kevinpapst/kimai2)"

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_PASSWORD}}

      - name: Build and push FPM Dev
        uses: docker/build-push-action@v3
        with:
          context: .
          target: dev
          build-args: |
            KIMAI=${{steps.remote_version.outputs.version}}
            TIMEZONE=Europe/London
            BASE=fpm
          tags: |
            kimai/kimai2:fpm-${{steps.remote_version.outputs.version}}-dev
            kimai/kimai2:fpm-dev
          push: true

      - name: Build and push FPM Prod
        uses: docker/build-push-action@v2
        with:
          context: .
          target: prod
          build-args: |
            KIMAI=${{steps.remote_version.outputs.version}}
            TIMEZONE=Europe/London
            BASE=fpm
          tags: |
            kimai/kimai2:fpm-${{steps.remote_version.outputs.version}}-prod
            kimai/kimai2:fpm-latest
            kimai/kimai2:fpm
            kimai/kimai2:latest
          push: true

      - name: Build and push Apache Dev
        uses: docker/build-push-action@v2
        with:
          context: .
          target: dev
          build-args: |
            KIMAI=${{steps.remote_version.outputs.version}}
            TIMEZONE=Europe/London
            BASE=apache
          tags: |
            kimai/kimai2:apache-${{steps.remote_version.outputs.version}}-dev
            kimai/kimai2:apache-dev
          push: true

      - name: Build and push Apache Prod
        uses: docker/build-push-action@v2
        with:
          context: .
          target: prod
          build-args: |
            KIMAI=${{steps.remote_version.outputs.version}}
            TIMEZONE=Europe/London
            BASE=apache
          tags: |
            kimai/kimai2:apache-${{steps.remote_version.outputs.version}}-prod
            kimai/kimai2:apache-latest
            kimai/kimai2:apache
          push: true

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
